/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.porschegt3cup.view;

import br.com.porschegt3cup.controller.TelaCadastroPecaController;
import br.com.porschegt3cup.controller.TelaEntradaPecaController;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author bruno
 */
public class TelaPecasEmRecuperacao extends javax.swing.JInternalFrame {

    private final TelaEntradaPecaController controller;

    /**
     * Creates new form TelaLocacao
     */
    public TelaPecasEmRecuperacao() {
        initComponents();
        controller = new TelaEntradaPecaController(this);
    }

    private boolean existeCamposObrigatoriosVazios() {

        if (txtidRecuperacao.getText().isEmpty()
                || cbMotivo.getSelectedItem().toString().isEmpty()) {
            return true;

        } else {
            return false;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        txtidRecuperacao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLPesquisar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPecasEmRecuperacao = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        rBtnPartNumber = new javax.swing.JRadioButton();
        rBtnDescricao = new javax.swing.JRadioButton();
        btnLimparCampos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cbFiltroSituacao = new javax.swing.JComboBox<>();
        cbFiltroSetor = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbAtualizarSituacao = new javax.swing.JComboBox<>();
        cbAtualizarSetor = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Tela Entrada Peças");
        setPreferredSize(new java.awt.Dimension(1530, 905));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Id");

        txtidRecuperacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtidRecuperacao.setPreferredSize(new java.awt.Dimension(500, 28));
        txtidRecuperacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidRecuperacaoKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Pesquisar por:");

        txtLPesquisar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLPesquisar.setPreferredSize(new java.awt.Dimension(500, 28));

        jLabel5.setText("_____________________________________________________________________________________________________________________________________________________");

        tblPecasEmRecuperacao = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblPecasEmRecuperacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Part Number", "Descrição", "Sub Sistema", "Chassis", "Etapa", "Data troca", "Situação", "Setor"
            }
        ));
        tblPecasEmRecuperacao.setFocusable(false);
        tblPecasEmRecuperacao.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblPecasEmRecuperacao);

        btnAtualizar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnAtualizar.setText("Registrar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("*Situação");

        buttonGroup1.add(rBtnPartNumber);
        rBtnPartNumber.setText("Part Number");

        buttonGroup1.add(rBtnDescricao);
        rBtnDescricao.setText("Descrição");

        btnLimparCampos.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnLimparCampos.setText("Limpar Busca");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbFiltroSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "EM ANALISE", "EM RECUPERACAO", "RECUPERADA", "DSI", "DESCARTE" }));

        cbFiltroSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "ESTOQUE", "MOTOR E CAMBIO", "OFICINA E FUNILARIA", "RECUPERACAO E DESENVOLVIMENTO", "RECUPERACAO EXTERNA", "ENGENHARIA" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Situação");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Setor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFiltroSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFiltroSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFiltroSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFiltroSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Filtros");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Atualizar Status");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("*Setor");

        cbAtualizarSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "EM ANALISE", "EM RECUPERACAO", "RECUPERADA", "DSI", "DESCARTE" }));

        cbAtualizarSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "ESTOQUE", "MOTOR E CAMBIO", "OFICINA E FUNILARIA", "RECUPERACAO E DESENVOLVIMENTO", "RECUPERACAO EXTERNA", "ENGENHARIA" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtLPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(rBtnPartNumber)
                                    .addGap(18, 18, 18)
                                    .addComponent(rBtnDescricao)
                                    .addGap(152, 152, 152))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnBuscar))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1039, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtidRecuperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(45, 45, 45)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbAtualizarSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbAtualizarSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(165, 165, 165)
                            .addComponent(jLabel8)))
                    .addComponent(btnLimparCampos))
                .addContainerGap(384, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rBtnPartNumber)
                            .addComponent(rBtnDescricao))
                        .addGap(14, 14, 14)
                        .addComponent(txtLPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnLimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtidRecuperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAtualizarSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAtualizarSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Locacao");

        setBounds(0, 0, 1530, 905);
    }// </editor-fold>//GEN-END:initComponents


    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

        if (existeCamposObrigatoriosVazios()) {
            JOptionPane.showMessageDialog(null, "é necessario preencher os campos obrigatórios paragistrar a entrada de uma peça");
        } else {
            controller.registrarEntrada();
        }

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        rBtnPartNumber.setSelected(true);
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtidRecuperacaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidRecuperacaoKeyTyped
        String caracteresPermitidos = "0123456789";
        if (!caracteresPermitidos.contains(evt.getKeyChar() + "")) {
            evt.consume();
    }//GEN-LAST:event_txtidRecuperacaoKeyTyped
    }
    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        controller.apagarCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbAtualizarSetor;
    private javax.swing.JComboBox<String> cbAtualizarSituacao;
    private javax.swing.JComboBox<String> cbFiltroSetor;
    private javax.swing.JComboBox<String> cbFiltroSituacao;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rBtnDescricao;
    private javax.swing.JRadioButton rBtnPartNumber;
    private javax.swing.JTable tblPecasEmRecuperacao;
    private javax.swing.JTextField txtLPesquisar;
    private javax.swing.JTextField txtidRecuperacao;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnRegistrar() {
        return btnAtualizar;
    }

    public void setBtnRegistrar(JButton btnRegistrar) {
        this.btnAtualizar = btnRegistrar;
    }

    public JComboBox<String> getCbMotivo() {
        return cbMotivo;
    }

    public void setCbMotivo(JComboBox<String> cbMotivo) {
        this.cbMotivo = cbMotivo;
    }

    public JRadioButton getrBtnDescricao() {
        return rBtnDescricao;
    }

    public void setrBtnDescricao(JRadioButton rBtnDescricao) {
        this.rBtnDescricao = rBtnDescricao;
    }

    public JRadioButton getrBtnPartNumber() {
        return rBtnPartNumber;
    }

    public void setrBtnPartNumber(JRadioButton rBtnPartNumber) {
        this.rBtnPartNumber = rBtnPartNumber;
    }

    public JTable getTblEntradaPeca() {
        return tblPecasEmRecuperacao;
    }

    public void setTblEntradaPeca(JTable tblEntradaPeca) {
        this.tblPecasEmRecuperacao = tblEntradaPeca;
    }

    public JTextField getTxtLPesquisar() {
        return txtLPesquisar;
    }

    public void setTxtLPesquisar(JTextField txtLPesquisar) {
        this.txtLPesquisar = txtLPesquisar;
    }

    public JTextField getTxtObservacao() {
        return txtObservacao;
    }

    public void setTxtObservacao(JTextField txtObservacao) {
        this.txtObservacao = txtObservacao;
    }

    public JTextField getTxtQuantidadeEntrada() {
        return txtidRecuperacao;
    }

    public void setTxtQuantidadeEntrada(JTextField txtQuantidadeEntrada) {
        this.txtidRecuperacao = txtQuantidadeEntrada;
    }
}
